export {
  buildCli,
  runCli,
  createLanguageRegistry,
  buildDefaultRegistry,
  discoverFiles,
  getSupportedGlobs,
  isTestFile,
  extractFromSource,
  processFile,
  runPipeline,
  detectFenceLanguage,
  formatFinalOutput,
  formatPlainOutput,
  toDisplayPath,
  toMarkdownCodeBlock,
} from "./main.js";

export {
  BUILT_IN_EXTRACT_KINDS,
  toPluginExtractKind,
  type AggregatedExtractResult,
  type BuiltInExtractKind,
  type CombinedExtractEntry,
  type DetectFenceLanguageOptions,
  type DiscoverFilesOptions,
  type ExtractEntry,
  type ExtractEntryMetadata,
  type ExtractFromSourceOptions,
  type ExtractKind,
  type ExtractWarning,
  type FileSection,
  type FormatFinalOutputOptions,
  type LanguageAdapter,
  type LanguageAdapterMetadata,
  type LanguageRegistry,
  type OutputFormat,
  type ParseContext,
  type PipelineDiagnostics,
  type PipelineError,
  type PipelineMeta,
  type PipelineResult,
  type PluginExtractKind,
  type ProcessFileOptions,
  type Range,
  type RunPipelineOptions,
  type SingleExtractResult,
  type TsParseContext,
} from "./00-core-types.js";
